### PR TITLE
Task 2

### PR DESCRIPTION
**Pull request by tlgadrkn**
Serverless-finch and serverless-single-page-app plugins are added and configured. 

S3 link: https://cloudx-aws-react-tolga.s3.us-east-2.amazonaws.com/index.html
Cloudfront: https://d10q3xm3y05eb6.cloudfront.net/

### CODE REVIEW

**Comment by 1MrSmith** [comment]
I can't see that the uploaded spa is available with content.
image

**Comment by tlgadrkn** [comment]
This is not a problem at this point. This task only checks if we were able to deploy the app. Application is deployed, visible and navigation works. Content will be visible when we will have backend I think. In fact they created a PR about network errors about this.

image

**Comment by 1MrSmith** [comment]
please update your configuration S3 section related to access(Restrict Bucket Access).
After deploying S3 with serverless and request by https://cloudx-aws-react-tolga.s3.us-east-2.amazonaws.com/ we have to see the page like this
image
In your case, I can see
image

**Comment by tlgadrkn** [comment]
> please update your configuration S3 section related to access(Restrict Bucket Access). After deploying S3 with serverless and request by https://cloudx-aws-react-tolga.s3.us-east-2.amazonaws.com/ we have to see the page like this image In your case, I can see image

Thanks for pointing this out. I updated the configuration.

**Comment by jas1337** [comment]
2.3.1 "Store the links to CloudFront URL and S3-website in README.md file."
Please add those links in appropriate markdown format to readme.

As @1MrSmith  mentioned, there are some issues on loading page content. 
Zrzut ekranu 2023-02-22 o 20 19 16

**Comment by tlgadrkn** [comment]
> 2.3.1 "Store the links to CloudFront URL and S3-website in README.md file." Please add those links in appropriate markdown format to readme.
> 
> As @1MrSmith mentioned, there are some issues on loading page content. Zrzut ekranu 2023-02-22 o 20 19 16

* Thanks, I  updated README.
*  as I explained to him, this is expected at this stage. Page content will be visible at task 3 when we create lambdas. This was discussed and verified in group chat.

**Pull request merged**
